### ISSUE TITLE
stuck in wsclean_ft?

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/factor#41] opened 2016-04-02 09:37 UTC
A disproportionate amount of time seems to be spent in the wsclean_ft step on my system. For example, it's been stuck this morning on the current facet (one of the biggest) for 3 hours on the same step (83 of 92). The command line it's running is

 <tt>/soft/wsclean/bin/wsclean -size 6804 6804 -channelsout 1 -tempdir /cair-forecast/mjh/P219p52/L337630_factor1_work/results/facetselfcal/facet_patch_500 -nwlayers-for-size 49152 49152 -j 8 -mem 45.0 -name /cair-forecast/mjh/P219p52/L337630_factor1_work/results/facetselfcal/facet_patch_500/L337630_SBgr018-10_uv.dppp.pre-cal_chunk12_1262B9382t_0g.wsclean_image_full2 -scale 0.000417 -predict /cair-forecast/mjh/P219p52/L337630_factor1_work/results/facetselfcal/facet_patch_500/L337630_SBgr018-10_uv.dppp.pre-cal_chunk0.shift_empty /cair-forecast/mjh/P219p52/L337630_factor1_work/results/facetselfcal/facet_patch_500/L337630_SBgr018-10_uv.dppp.pre-cal_chunk1.shift_empty ...</tt>

I am not sure where the -j8 -mem 45 is coming from, but in any case it's running single-threaded with very occasional bursts of 8 threads. This one step of wsclean_ft has taken a comparable time to the entire operation on one facet on the same system in the manual scripts, which is a bit worrying. Anyone else seeing a similar thing? wsclean is v 1.11.

**Comment by AHorneffer** [comment] 2016-04-02 13:06
It is the "generate full-res visibilities for the full facet" step. The -j 8 and -mem 45 are computed from the ncpu and fmem values in the factor parset divided by nimg_per_node. 

I don't know why WSClean isn't using the 8 threads it was told that it can use. Is it running out of memory?

**Comment by mhardcastle** [comment] 2016-04-02 14:33
Yes I figured out that the memory was being restricted by the nimg_per_node (which seems a bit unnecessary here as no other imagers are running). I'm running a copy of the same command line on another node to see if it makes a difference. 

Is computing a number of wlayers appropriate for a 50,000 x 50,000 image really required?

**Comment by mhardcastle** [comment] 2016-04-02 15:25
Update... running with the full memory and CPU of the node makes no very obvious difference. It's just slow because it's doing many, many passes (which are single-threaded because they involve a FFT; I don't think wsclean uses multi-threaded FFTW) and presumably because there are a lot of clean components in this big facet. So, I think we're back to the question of whether this number of wlayers is really necessary? It looks like the execution time is going to go as the square of the image size selected, so using a number closer to the actual final image size would give something approaching an order of magnitude improvement in execution time.

**Comment by rvweeren** [comment] 2016-04-02 15:31
I also see rather low-CPU usage on my machine (24 cores). David put in the 50,000 x 50,000 to avoid aliasing. (Andre recommended using an image size up the the largest sky area covered). Strange thing is that the aliasing is really bad at the moment...

**Comment by mhardcastle** [comment] 2016-04-02 16:44
But we don't go out to 20 x 20 degrees or anything like it, surely? The main imaging area seems to be about 5.5 degrees diameter, which would imply 14,000 x 14,000 would do it. I guess there's the issue of bright sources a long way off axis, but even so, this seems like overkill.

**Comment by rvweeren** [comment] 2016-04-02 16:49
Yes, I think that we can reduce nwlayers-for-size to something like twice the image size (with a minimum of 8192 or so). Unless it is clear it is important to make it as large as 49152. Clearly this does not really help to reduce aliasing at all (and that was the reason for using these large values in the first place). So my conclusion is that the aliasing we see is not really related to the number of w-planes. So (1) we need to pad the -model.fits images and (2) we can use much more modest values for -nwlayers-for-size (with the advantage of speeding up this step).

**Comment by darafferty** [comment] 2016-04-02 19:24
I didn't see much of a performance hit in going from 12288 to 49162 in my testing (note that a 5.5 degree diameter field implies an image of 11 degrees across to cover it if it's centered at the edge of the field) . But I also didn't see any real improvement in the aliasing issue either when I increased it. I will add the padding back in (it was there in previous versions) and hopefully this issue will be fixed.

**Comment by rvweeren** [comment] 2016-04-02 19:46
Ok, I'll test it when the padding is added back and do a full comparision (maybe we should increase the default padding to 1.4 in factor, just to be safe, since the aliasing is so severe).

**Comment by mhardcastle** [comment] 2016-04-02 19:50
The image size for wplanes clearly makes a big difference in my testing. Obviously if you have almost no clean components to grid it's possible that you're scaling almost nothing up by a large factor and it still doesn't matter. The wsclean_ft for the tiny facet around 3C295 in my test run was very quick.

**Comment by darafferty** [comment] 2016-04-04 09:36
OK, that makes sense. I will add the padding back in today.

**Comment by mhardcastle** [comment] 2016-04-04 09:52
And I would suggest going back to 12288 x 12288 for wplanes in the parset.

**Comment by darafferty** [comment] 2016-04-04 12:58
I added the padding and reduced the wplanes to 12288, but only in the facetpeel branch. See issue #40 for details.

**Comment by rvweeren** [comment] 2016-04-08 18:24
Performance also improved for me. I do not see any issue with aliasing related to the change from nwlayers-for-size 49152 to 12288, so this can be pushed into the master branch. Then we can close this issue.

**Comment by rvweeren** [comment] 2016-04-14 17:54
Can someone with the right permissions close this issue? (confirmed it is fixed)

**Closed as completed** 2016-04-14 18:05 UTC
