### ISSUE TITLE
checkfactor missing a step?

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/factor#43] opened 2016-04-02 21:28 UTC
After wsclean_ft checkfactor returns errors: 
ValueError: 'regroup_shift_empty' is not in list
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/matplotlib/backend_bases.py", line 1305, in _on_timer
    ret = func(_args, *_kwargs)
  File "/home/mjh/git/factor/build/lib/factor/check_progress.py", line 442, in update_plot
    info = get_current_info(d)
  File "/home/mjh/git/factor/build/lib/factor/check_progress.py", line 326, in get_current_info
    current_step, current_index, num_steps, start_time = get_current_step(direction)
  File "/home/mjh/git/factor/build/lib/factor/check_progress.py", line 681, in get_current_step
    current_index = current_steps.index(previous_step_name) + abs(prev_indx+1) + 1
ValueError: 'regroup_shift_empty' is not in list

**Comment by mhardcastle** [comment] 2016-04-03 09:44
Also average5_sorted_groups is not in the list, same error.

**Comment by mhardcastle** [comment] 2016-04-03 10:02
I've put a try-except block in the code to catch the ValueError in current_steps.index(previous_step_name). At least this way we don't get errors all over the console.

**Comment by darafferty** [comment] 2016-04-04 09:30
HI Martin - this issue should have been fixed about a week ago (with a similar try-except block, see #35). Do you have the latest version? If so, there must be some cases that aren't being caught for some reason.

**Comment by mhardcastle** [comment] 2016-04-04 09:45
This was a git pull from yesterday, so I'm pretty sure something wasn't being caught by earlier changes. The case that triggers the error is when previous_step_name is not in current_steps (perhaps because stuff gets done to the current_steps list when it's extracted from the parset)?

**Comment by darafferty** [comment] 2016-04-04 10:32
Ah, yes, that could be the cause.

**Comment by darafferty** [comment] 2016-04-19 11:36
I just fixed another a minor bug that was causing it to fail to find the correct current step. With that, I think these problems are fixed now, so I'll close this issue.

**Closed as completed by darafferty** 2016-04-19 11:36 UTC
